const path=require('path'); const { ChannelType, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, AttachmentBuilder }=require('discord.js');
const config=require('./config'); const {read,write}=require('./jsonStore'); const logger=require('./logger');
const ticketsFile=path.join(config.root,'data','tickets.json'); const countersFile=path.join(config.root,'data','counters.json');
const types=['support','purchase'];
function all(){ return read(ticketsFile, []); } function save(rows){ write(ticketsFile, rows); }
function byChannel(id){ return all().find(t=>t.channelId===id); } function byOwner(ownerId,type){ return all().find(t=>t.ownerId===ownerId && t.type===type); }
function remove(channelId){ save(all().filter(t=>t.channelId!==channelId)); }
function update(channelId, patch){ save(all().map(t=>t.channelId===channelId?{...t,...patch}:t)); }
function nextId(type){ const c=read(countersFile,{support:0,purchase:0}); c[type]=(c[type]||0)+1; write(countersFile,c); return String(c[type]).padStart(3,'0'); }
function style(name){ return ButtonStyle[name] || ButtonStyle.Primary; }
function fmt(s, vars){ return String(s||'').replace(/\{(\w+)\}/g,(_,k)=>vars[k]??''); }
async function create(interaction,type){ const panel=config.panel(type); const msg=config.get('messages'); if(!panel.enabled) return interaction.reply({content:msg.ticketsDisabled,ephemeral:true}); const existing=byOwner(interaction.user.id,type); if(existing) return interaction.reply({content:fmt(msg.ticketExists,{type,channel:`<#${existing.channelId}>`}),ephemeral:true}); const id=nextId(type); const guild=interaction.guild; const ch=await guild.channels.create({name:`${type}-${id}`,type:ChannelType.GuildText,parent:panel.categoryId,permissionOverwrites:[{id:guild.id,deny:[PermissionFlagsBits.ViewChannel]},{id:interaction.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:panel.staffRoleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.ManageMessages]}]}); const rec={id,type,channelId:ch.id,ownerId:interaction.user.id,createdAt:Date.now(),claimedBy:null}; save([...all(),rec]); const emb=new EmbedBuilder().setColor(panel.embedColor).setTitle(`${panel.panelTitle} #${id}`).setDescription(fmt(panel.welcomeMessage,{user:`<@${interaction.user.id}>`})).setTimestamp(); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_claim').setLabel('Claim').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('ticket_close').setLabel('Close').setStyle(ButtonStyle.Danger)); await ch.send({content:`<@${interaction.user.id}> <@&${panel.staffRoleId}>`,embeds:[emb],components:[row]}); await interaction.reply({content:fmt(msg.ticketCreated,{type,channel:`<#${ch.id}>`}),ephemeral:true}); await logger.log(interaction.client,'ticketCreate',`${type} ticket ${ch.name} created by ${interaction.user.tag}`); }
async function transcript(channel){ const messages=await channel.messages.fetch({limit:100}); const ticket=byChannel(channel.id); let html=`<!doctype html><meta charset="utf-8"><title>${channel.name}</title><body><h1>${channel.name}</h1>`; for(const m of [...messages.values()].reverse()) html+=`<p><b>${m.author.tag}</b> <small>${m.createdAt.toISOString()}</small><br>${m.content.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</p>`; html+='</body>'; const file=path.join(config.root,'logs','transcripts',`${channel.name}-${Date.now()}.html`); require('fs').writeFileSync(file,html); const bot=config.get('bot'); const dest=bot.transcriptChannelId && await channel.client.channels.fetch(bot.transcriptChannelId).catch(()=>null); if(dest) await dest.send({content:`Transcript for ${channel.name}${ticket?` (owner <@${ticket.ownerId}>)`:''}`,files:[new AttachmentBuilder(file)]}); await logger.log(channel.client,'transcript',`Transcript generated for ${channel.name}`); return file; }
async function close(channel){ const t=byChannel(channel.id); const panel=t&&config.panel(t.type); await channel.send(panel?.closeMessage||'Closing ticket.'); await transcript(channel); remove(channel.id); await logger.log(channel.client,'ticketClose',`${channel.name} closed`); const delay=(config.get('bot').deleteDelaySeconds??5)*1000; setTimeout(()=>channel.delete().catch(logger.error),delay); }
module.exports={types,all,save,byChannel,byOwner,remove,update,create,transcript,close,fmt,style};
